services:
  # PHP Application
  app:
    build:
      context: .
      dockerfile: Dockerfile.php
    container_name: miscvord_php
    restart: unless-stopped
    # For production, consider building code into the image and removing these code volumes
    # Or, if you deploy by syncing code to the VPS and then running docker-compose, these are fine.
    volumes:
      - ./public:/var/www/html/public:ro
      - ./views:/var/www/html/views:ro
      - ./controllers:/var/www/html/controllers:ro
      - ./config:/var/www/html/config:ro
      - ./bootstrap:/var/www/html/bootstrap:ro
      - ./migrations:/var/www/html/migrations:ro
      - ./database:/var/www/html/database:ro
      - ./utils:/var/www/html/utils:ro
      - ./storage:/var/www/html/storage:rw # Ensure this is writable for uploads/logs
      - ./router.php:/var/www/html/router.php:ro
      - ./index.php:/var/www/html/index.php:ro
      - ./.htaccess:/var/www/html/.htaccess:ro
    depends_on:
      - db
    networks:
      - miscvord_network
    ports: # Ports exposed to the host
      - "${APP_PORT:-1001}:1001"
    environment:
      - APP_ENV=${APP_ENV:-production} # Set to production for VPS
      - APP_DEBUG=${APP_DEBUG:-false}  # Set to false for VPS
      - DB_HOST=db
      - DB_PORT=${DB_PORT:-1003}
      - DB_NAME=${DB_NAME:-misvord}
      - DB_USER=${DB_USER:-root}
      - DB_PASS=${DB_PASS:-password} # Use .env file for this!
      - DB_CHARSET=${DB_CHARSET:-utf8mb4}
      # Environment Detection
      - IS_VPS=${IS_VPS:-true} # Set to true for VPS
      - USE_HTTPS=${USE_HTTPS:-true} # Set to true for VPS
      - DOMAIN=${DOMAIN:-marvelcollin.my.id} # Set to your domain
      - PORT=1001 # Internal port for PHP service
      # VideoSDK Configuration
      - VIDEOSDK_API_KEY=${VIDEOSDK_API_KEY}
      - VIDEOSDK_SECRET_KEY=${VIDEOSDK_SECRET_KEY}
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  # MySQL Database
  db:
    image: mysql:8.0
    container_name: miscvord_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME:-misvord}
      MYSQL_ROOT_PASSWORD: ${DB_PASS:-password} # Use .env file for this!
      MYSQL_ROOT_HOST: "%"
      MYSQL_TCP_PORT: ${DB_PORT:-1003}
    volumes:
      - miscvord_db_data:/var/lib/mysql # Persists DB data on the host
    networks:
      - miscvord_network
    # ports: # Usually kept internal unless direct host access is needed
    #   - "${DB_PORT:-1003}:${DB_PORT:-1003}"
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --port=${DB_PORT:-1003}
    security_opt:
      - seccomp:unconfined # Required by MySQL for some operations
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-P", "${DB_PORT:-1003}"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  # Enhanced PHPMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: miscvord_phpmyadmin
    depends_on:
      - db
    networks:
      - miscvord_network
    ports: # Ports exposed to the host
     - "${PMA_PORT:-1004}:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=${DB_PORT:-1003}
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=500M
      - PMA_USER=${DB_USER:-root}
      - PMA_PASSWORD=${DB_PASS:-password} # Use .env file for this!
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

  adminer:
    image: adminer
    container_name: miscvord_adminer
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - miscvord_network
    ports: # Ports exposed to the host
     - "${ADMINER_PORT:-1005}:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: pepa-linha # Example theme
    security_opt:
      - no-new-privileges:true

networks:
  miscvord_network:
    driver: bridge

volumes:
  miscvord_db_data: # Defines the volume for MySQL data persistence
    driver: local # Explicitly define as local driver
