version: '3.8'

services:
  # PHP Application
  app:
    build:
      context: .
      dockerfile: Dockerfile.php
    container_name: miscvord_php
    restart: unless-stopped
    volumes:
      - ./public:/var/www/html/public:ro
      - ./views:/var/www/html/views:ro
      - ./controllers:/var/www/html/controllers:ro
      - ./config:/var/www/html/config:ro 
      - ./bootstrap:/var/www/html/bootstrap:ro
      - ./migrations:/var/www/html/migrations:ro
      - ./storage:/var/www/html/storage:rw
    depends_on:
      - socket-server
      - db
    networks:
      - miscvord_network
    ports:
      - "1001:80"
    environment:
      - APP_ENV=production
      - DB_HOST=db
      - DB_NAME=misvord
      - DB_USER=root
      - DB_PASS=MiscVord_secure_2023
      - DB_CHARSET=utf8mb4
      - SOCKET_SERVER=http://socket-server:3000
      - SOCKET_API_KEY=kolin123
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Unified Socket.io Server
  socket-server:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: miscvord_socket
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - miscvord_network
    ports:
      - "1002:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - SOCKET_API_KEY=kolin123
      - DB_HOST=db
      - DB_NAME=misvord
      - DB_USER=root
      - DB_PASS=MiscVord_secure_2023
    security_opt:
      - no-new-privileges:true
    ulimits:
      nofile:
        soft: 1024
        hard: 2048
    healthcheck:
      test: ["CMD", "wget", "--spider", "--no-verbose", "http://localhost:3000/health" , "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # MySQL Database
  db:
    image: mysql:8.0
    container_name: miscvord_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: misvord
      MYSQL_ROOT_PASSWORD: MiscVord_secure_2023
      MYSQL_ROOT_HOST: "%"
    volumes:
      - miscvord_db_data:/var/lib/mysql
    networks:
      - miscvord_network
    ports:
      - "1003:3306"
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    security_opt:
      - seccomp:unconfined
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  # Enhanced PHPMyAdmin 
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: miscvord_phpmyadmin
    depends_on:
      - db
    networks:
      - miscvord_network
    ports:
      - "1004:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=500M
      - PMA_USER=root
      - PMA_PASSWORD=MiscVord_secure_2023
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

  adminer:
    image: adminer
    container_name: miscvord_adminer
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - miscvord_network
    ports:
      - "1005:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: pepa-linha
    security_opt:
      - no-new-privileges:true

networks:
  miscvord_network:
    driver: bridge

volumes:
  miscvord_db_data:
