services:
  # PHP Application
  app:
    build:
      context: .
      dockerfile: Dockerfile.php
    container_name: misvord_php
    restart: unless-stopped
    volumes:
      - ./public:/var/www/html/public:ro
      - ./views:/var/www/html/views:ro
      - ./controllers:/var/www/html/controllers:ro
      - ./config:/var/www/html/config:ro
      - ./bootstrap:/var/www/html/bootstrap:ro
      - ./migrations:/var/www/html/migrations:ro
      - ./database:/var/www/html/database:ro
      - ./utils:/var/www/html/utils:ro
      - ./storage:/var/www/html/storage:rw
      - ./public/router.php:/var/www/html/router.php:ro
      - ./public/index.php:/var/www/html/index.php:ro
      - ./.htaccess:/var/www/html/.htaccess:ro
      - ./public/storage:/var/www/html/public/storage:rw
    depends_on:
      - db
    networks:
      - misvord_network
    ports: 
      - "${APP_PORT:-1001}:1001"
    environment:
      - APP_ENV=${APP_ENV:-production} 
      - APP_DEBUG=${APP_DEBUG:-false} 
      - DB_HOST=db
      - DB_PORT=1003
      - DB_NAME=misvord
      - DB_USER=root
      - DB_PASS=kolin123
      - DB_CHARSET=utf8mb4
      - IS_VPS=${IS_VPS:-true} 
      - USE_HTTPS=${USE_HTTPS:-true} 
      - DOMAIN=${DOMAIN:-marvelcollin.my.id}
      - PORT=1001
      - SOCKET_HOST=${SOCKET_HOST:-socket}
      - SOCKET_PORT=${SOCKET_PORT:-1002}
      - VIDEOSDK_API_KEY=${VIDEOSDK_API_KEY}
      - VIDEOSDK_SECRET_KEY=${VIDEOSDK_SECRET_KEY}
      - VIDEOSDK_TOKEN=${VIDEOSDK_TOKEN}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Socket.IO Server
  socket:
    build:
      context: ./socket-server
      dockerfile: Dockerfile
    container_name: misvord_socket
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - misvord_network
    ports:
      - "${SOCKET_PORT:-1002}:1002"
    environment:
      - DB_HOST=db
      - DB_PORT=1003
      - DB_NAME=misvord
      - DB_USER=root
      - DB_PASS=kolin123
      - SOCKET_PORT=1002
      - SOCKET_BASE_PATH=/socket.io
      - CORS_ALLOWED_ORIGINS=http://localhost:1001,http://127.0.0.1:1001,http://misvord_php:1001,${DOMAIN:-marvelcollin.my.id}
    volumes:
      - ./socket-server:/app
      - /app/node_modules
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  db:
    image: mysql:8.0
    container_name: misvord_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: misvord
      MYSQL_ROOT_PASSWORD: kolin123
      MYSQL_ROOT_HOST: "%"
      MYSQL_TCP_PORT: 1003
    volumes:
      - misvord_db_data:/var/lib/mysql
      - ./docker/mysql-init:/docker-entrypoint-initdb.d
    networks:
      - misvord_network
    ports:
      - "1003:1003"
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --port=1003
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-P", "1003", "-u", "root", "-pkolin123"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: misvord_phpmyadmin
    depends_on:
      - db
    networks:
      - misvord_network
    ports:
      - "1004:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 1003
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 500M
      PMA_USER: root
      PMA_PASSWORD: kolin123
      MYSQL_ROOT_PASSWORD: kolin123
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

  adminer:
    image: adminer
    container_name: misvord_adminer
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - misvord_network
    ports: 
     - "1005:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: pepa-linha 
    security_opt:
      - no-new-privileges:true

networks:
  misvord_network:
    driver: bridge

volumes:
  misvord_db_data: 
    driver: local