FROM node:20.11.0-alpine3.19

WORKDIR /app

COPY package*.json ./

RUN npm install && npm install -g nodemon

COPY socket-server.js server.js package.json ./

EXPOSE 3000

CMD ["nodemon", "socket-server.js"]