version: '3.8'

services:
  # PHP Application
  app:
    build:
      context: .
      dockerfile: Dockerfile.php
    container_name: miscvord_php
    restart: unless-stopped
    volumes:
      - ./public:/var/www/html/public:ro
      - ./views:/var/www/html/views:ro
      - ./controllers:/var/www/html/controllers:ro
      - ./config:/var/www/html/config:ro
      - ./bootstrap:/var/www/html/bootstrap:ro
      - ./migrations:/var/www/html/migrations:ro
      - ./database:/var/www/html/database:ro
      - ./utils:/var/www/html/utils:ro
      - ./storage:/var/www/html/storage:rw
      - ./router.php:/var/www/html/router.php:ro
      - ./index.php:/var/www/html/index.php:ro
      - ./.htaccess:/var/www/html/.htaccess:ro
    depends_on:
      - socket-server
      - db
    networks:
      - miscvord_network
    ports:
      - "${APP_PORT:-1001}:80"
    environment:
      - APP_ENV=${APP_ENV:-local}
      - APP_DEBUG=${APP_DEBUG:-true}
      - DB_HOST=db
      - DB_PORT=${DB_PORT:-1003}
      - DB_NAME=${DB_NAME:-misvord}
      - DB_USER=${DB_USER:-root}
      - DB_PASS=${DB_PASS:-password}
      - DB_CHARSET=${DB_CHARSET:-utf8mb4}
      - SOCKET_SERVER=${SOCKET_SERVER:-http://socket-server:1002}
      - SOCKET_SERVER_LOCAL=${SOCKET_SERVER_LOCAL:-http://localhost:1002}
      - SOCKET_API_KEY=${SOCKET_API_KEY:-kolin123}
      - IS_VPS=${IS_VPS:-false}
      - DOMAIN=${DOMAIN:-localhost}
      - SUBPATH=${SUBPATH:-misvord}
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Unified Socket.io Server
  socket-server:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: miscvord_socket
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - miscvord_network
    ports:
      - "${SOCKET_PORT:-1002}:1002"
      - "${SOCKET_SECURE_PORT:-1443}:1443" # Added secure port for HTTPS/WSS
    environment:
      - NODE_ENV=${APP_ENV:-local}
      - PORT=${SOCKET_PORT:-1002}
      - SECURE_PORT=${SOCKET_SECURE_PORT:-1443}
      - SOCKET_API_KEY=${SOCKET_API_KEY:-kolin123}
      - DB_HOST=db
      - DB_PORT=${DB_PORT:-1003}
      - DB_NAME=${DB_NAME:-misvord}
      - DB_USER=${DB_USER:-root}
      - DB_PASS=${DB_PASS:-password}
      - SOCKET_URL=${SOCKET_SERVER:-http://socket-server:1002}
      - SOCKET_PATH=${SOCKET_PATH:-/socket.io}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-*}
      - USE_HTTPS=${USE_HTTPS:-false}
      - IS_VPS=${IS_VPS:-false}
      - DOMAIN=${DOMAIN:-localhost}
      - SUBPATH=${SUBPATH:-misvord}
    security_opt:
      - no-new-privileges:true
    ulimits:
      nofile:
        soft: 1024
        hard: 2048
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://localhost:1002/health" , "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # MySQL Database
  db:
    image: mysql:8.0
    container_name: miscvord_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME:-misvord}
      MYSQL_ROOT_PASSWORD: ${DB_PASS:-password}
      MYSQL_ROOT_HOST: "%"
      MYSQL_TCP_PORT: ${DB_PORT:-1003}
    volumes:
      - miscvord_db_data:/var/lib/mysql
    networks:
      - miscvord_network
    ports:
      - "${DB_PORT:-1003}:${DB_PORT:-1003}"
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --port=${DB_PORT:-1003}
    security_opt:
      - seccomp:unconfined
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-P", "${DB_PORT:-1003}"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  # Enhanced PHPMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: miscvord_phpmyadmin
    depends_on:
      - db
    networks:
      - miscvord_network
    ports:
      - "${PMA_PORT:-1004}:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=${DB_PORT:-1003}
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=500M
      - PMA_USER=${DB_USER:-root}
      - PMA_PASSWORD=${DB_PASS:-password}
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

  adminer:
    image: adminer
    container_name: miscvord_adminer
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - miscvord_network
    ports:
      - "${ADMINER_PORT:-1005}:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: pepa-linha
    security_opt:
      - no-new-privileges:true

networks:
  miscvord_network:
    driver: bridge

volumes:
  miscvord_db_data:
