FROM node:18

# Create app directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install app dependencies
RUN npm install

# Copy app source
COPY . .

# Expose port for the socket server
EXPOSE 3000

# Start the unified socket server
CMD ["npm", "run", "dev"] 